[package]
name = "monitor-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nvml-wrapper = "0.10.0"
nvml-wrapper-sys = "0.8.0"
